export interface RestAPIResponse {
  token: string
  user: User
}

export interface User {
  email: string
  username: string
  role: 'ADMIN' | 'SALESPERSON'
}
// Generated by https://quicktype.io

export interface UserData {
  id: string
  email: string
  username: string
  role: 'ADMIN' | 'SALESPERSON'
}
